# Generated by Django 5.2.17 on 2026-09-08 18:53

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("principal_id", models.UUIDField()),
                ("authenticated_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("last_activity_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("expires_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "revoked_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        blank=True, null=True
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stewardship_portal",
                        to="sessions.session",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_portal_session",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["principal_id", "revoked_at"],
                        name="portal_session_principal",
                    ),
                    models.Index(fields=["expires_at"], name="portal_session_expiry"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_portalsession_positive_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gt", models.F("authenticated_at"))
                        ),
                        name="portal_session_positive_lifetime",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("last_activity_at__gte", models.F("authenticated_at"))
                        ),
                        name="portal_session_activity_after_auth",
                    ),
                ],
            },
        ),
    ]
