# Generated by Django 5.2.17 on 2026-09-08 20:20

import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("stewardship_accounts", "0003_version_guard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalsession",
            name="created_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="portalsession",
            name="updated_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True),
                    ("revoked_at__gte", models.F("last_activity_at")),
                    _connector="OR",
                ),
                name="portal_session_no_activity_after_revoke",
            ),
        ),
    ]
