# Generated by Django 5.2.17 on 2026-09-08 21:58

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0004_alter_portalsession_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedConfigurationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("canonical_document", models.JSONField()),
                ("normalized_digest", models.CharField(max_length=64)),
                ("validation_schema", models.CharField(max_length=64)),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_configuration_version",
            },
        ),
        migrations.CreateModel(
            name="AppliedIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField()),
                ("kind", models.CharField(max_length=32)),
                ("settings", models.JSONField()),
                (
                    "credential_fingerprint",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integrations",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_applied_integration",
            },
        ),
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=254)),
                ("website", models.URLField(max_length=2048)),
                ("timezone", models.CharField(max_length=254)),
                ("phone", models.CharField(max_length=12)),
                ("large_logo_id", models.UUIDField()),
                ("menu_logo_id", models.UUIDField()),
                ("icon_logo_id", models.UUIDField()),
                ("favicon_id", models.UUIDField()),
                (
                    "configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parish",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_parish",
            },
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(predecessor__isnull=True),
                name="configuration_single_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version", 1)),
                name="configuration_schema_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("digest__regex", "^[0-9a-f]{64}$"),
                    ("normalized_digest__regex", "^[0-9a-f]{64}$"),
                ),
                name="configuration_valid_digests",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("predecessor_id", models.F("id")), _negated=True),
                name="configuration_not_own_predecessor",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedintegration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "kind"), name="configuration_integration_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedintegration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"),
                name="configuration_integration_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedintegration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "parishsoft",
                            "google_oauth",
                            "google_workspace",
                            "email",
                            "slack",
                            "backup",
                        ],
                    )
                ),
                name="integration_known_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedintegration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("credential_fingerprint__isnull", True),
                    ("credential_fingerprint__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="integration_safe_fingerprint",
            ),
        ),
    ]
