# Generated by Django 5.2.17 on 2026-09-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0006_configuration_guards"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("validation_schema", "parish-integrations-v1")),
                name="configuration_validation_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="parish",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("name", ""), _negated=True),
                    models.Q(("timezone", ""), _negated=True),
                ),
                name="parish_nonempty_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="parish",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone__regex", "^\\+1[2-9][0-9]{2}[2-9][0-9]{6}$")
                ),
                name="parish_us_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="parish",
            constraint=models.CheckConstraint(
                condition=models.Q(("website__iregex", "^https?://")),
                name="parish_website_scheme",
            ),
        ),
    ]
