# Generated by Django 5.2.17 on 2026-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship_accounts",
            "0007_appliedconfigurationversion_configuration_validation_schema_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appliedconfigurationversion",
            name="configuration_validation_schema",
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("validation_schema__in", ["parish-integrations-v1"])
                ),
                name="configuration_validation_schema",
            ),
        ),
    ]
