# Generated by Django 5.2.17 on 2026-09-09 03:23

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship_accounts",
            "0008_remove_appliedconfigurationversion_configuration_validation_schema_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("request_schema", models.CharField(max_length=64)),
                ("patch", models.JSONField()),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("candidate_version_id", models.UUIDField(unique=True)),
                ("candidate_digest", models.CharField(max_length=64, unique=True)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_config_request",
            },
        ),
        migrations.CreateModel(
            name="ConfigurationRequestCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("state", models.CharField(max_length=16)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="stewardship_accounts.configurationchangerequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_config_checkpoint",
            },
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(request_schema__in=["parish-integrations-patch-v1"]),
                name="config_request_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.UniqueConstraint(
                fields=("actor_id", "request_key"), name="config_request_actor_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("actor_id__isnull", False)),
                name="config_request_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("payload_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="config_request_payload_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("candidate_digest__regex", "^[0-9a-f]{64}$")),
                name="config_request_candidate_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationrequestcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("request", "sequence"), name="config_checkpoint_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationrequestcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="config_checkpoint_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationrequestcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["staged", "cancelled"])),
                name="config_checkpoint_intake_states",
            ),
        ),
    ]
