# Generated by Django 5.2.17 on 2026-09-09 11:23

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0010_request_intake_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(unique=True)),
                (
                    "configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_successors",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation",
                        to="stewardship_accounts.configurationchangerequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_config_activation",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="activation_positive_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("predecessor__isnull", True),
                                ("request__isnull", True),
                                ("sequence", 1),
                            ),
                            models.Q(
                                ("predecessor__isnull", False),
                                ("request__isnull", False),
                                ("sequence__gt", 1),
                            ),
                            _connector="OR",
                        ),
                        name="activation_bootstrap_or_request",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("mode", models.CharField(default="testing", max_length=16)),
                ("testing_recipient", models.EmailField(max_length=254)),
                ("restore_review_required", models.BooleanField(default=False)),
                (
                    "active_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_system_configuration",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_systemconfiguration_positive_version",
                    ),
                    models.UniqueConstraint(
                        models.Value(1), name="system_configuration_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mode", "testing")),
                        name="system_testing_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "testing_recipient__regex",
                                "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
                            )
                        ),
                        name="system_testing_recipient",
                    ),
                ],
            },
        ),
    ]
