# Generated by Django 5.2.17 on 2026-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0011_configurationactivation_systemconfiguration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configurationrequestcheckpoint",
            name="config_checkpoint_intake_states",
        ),
        migrations.AddField(
            model_name="configurationrequestcheckpoint",
            name="failure_code",
            field=models.CharField(db_default="", default="", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="configurationrequestcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "staged",
                            "validating",
                            "prepared",
                            "yaml_activated",
                            "applied",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="config_checkpoint_installer_states",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationrequestcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("failure_code__in", ["stale_base", "invalid_candidate"]),
                        ("state", "failed"),
                    ),
                    models.Q(
                        models.Q(("state", "failed"), _negated=True),
                        ("failure_code", ""),
                    ),
                    _connector="OR",
                ),
                name="config_checkpoint_failure_code",
            ),
        ),
    ]
