# Generated by Django 5.2.17 on 2026-09-09 14:50

import uuid
from datetime import timedelta

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0013_activation_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretReplacementRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("target", models.CharField(max_length=32)),
                ("staging_reference", models.UUIDField(unique=True)),
                ("requested_by_id", models.UUIDField()),
                (
                    "reauthenticated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(),
                ),
                ("expires_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "expected_fingerprint",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        db_default="staged", default="staged", max_length=16
                    ),
                ),
                (
                    "cleanup_reason",
                    models.CharField(db_default="", default="", max_length=16),
                ),
                (
                    "scrubbed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        blank=True, null=True
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_secret_request",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["state", "expires_at"], name="secret_expiry")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_secretreplacementrequest_positive_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ["staged", "cleanup_pending"])
                        ),
                        fields=("target",),
                        name="secret_one_pending_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "target__in",
                                (
                                    "django_signing",
                                    "general_encryption",
                                    "family_code_mac",
                                    "token_public",
                                    "token_private",
                                    "google_oauth",
                                    "google_workspace",
                                    "parishsoft",
                                    "slack",
                                    "backup_target",
                                    "backup_data",
                                    "metrics",
                                ),
                            )
                        ),
                        name="secret_known_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("staged", "cleanup_pending", "cancelled", "expired"),
                            )
                        ),
                        name="secret_known_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reauthenticated_at__lte", models.F("created_at")),
                            ("expires_at__gt", models.F("created_at")),
                        ),
                        name="secret_valid_interval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            expires_at__lte=models.F("created_at") + timedelta(hours=24)
                        ),
                        name="secret_max_staging_lifetime",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_fingerprint__isnull", True),
                            ("expected_fingerprint__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="secret_safe_fingerprint",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("cleanup_reason", ""),
                                ("scrubbed_at__isnull", True),
                                ("state", "staged"),
                            ),
                            models.Q(
                                ("cleanup_reason__in", ["cancelled", "expired"]),
                                ("scrubbed_at__isnull", True),
                                ("state", "cleanup_pending"),
                            ),
                            models.Q(
                                ("cleanup_reason", models.F("state")),
                                ("scrubbed_at__isnull", False),
                                ("state__in", ["cancelled", "expired"]),
                                ("scrubbed_at__gte", models.F("created_at")),
                            ),
                            _connector="OR",
                        ),
                        name="secret_cleanup_shape",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretRequestCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("state", models.CharField(max_length=16)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkpoints",
                        to="stewardship_accounts.secretreplacementrequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_secret_checkpoint",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "sequence"),
                        name="secret_checkpoint_sequence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)),
                        name="secret_checkpoint_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("staged", "cleanup_pending", "cancelled", "expired"),
                            )
                        ),
                        name="secret_checkpoint_state",
                    ),
                ],
            },
        ),
    ]
