# Generated by Django 5.2.17 on 2026-09-09 20:58

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0015_secret_request_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressRoleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("role", models.CharField(max_length=32)),
                ("origins", models.JSONField()),
            ],
            options={
                "db_table": "stewardship_address_grant",
            },
        ),
        migrations.CreateModel(
            name="AddressRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField()),
                ("email", models.EmailField(max_length=254)),
                ("roles", models.JSONField()),
                ("creation_origin", models.CharField(max_length=16)),
                ("creation_operation", models.UUIDField()),
            ],
            options={
                "db_table": "stewardship_address_rule",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssignmentOverlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("assignment_record_id", models.UUIDField(unique=True)),
                ("active", models.BooleanField()),
                ("source_snapshot_id", models.UUIDField()),
                ("reason", models.CharField(max_length=32)),
            ],
            options={
                "db_table": "stewardship_assignment_overlay",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomainRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField()),
                ("domain", models.CharField(max_length=253)),
                ("roles", models.JSONField()),
            ],
            options={
                "db_table": "stewardship_domain_rule",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinistryAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField()),
                ("email", models.EmailField(max_length=254)),
                ("ministry_duid", models.PositiveBigIntegerField()),
                ("source", models.CharField(max_length=16)),
                ("operation_id", models.UUIDField()),
            ],
            options={
                "db_table": "stewardship_ministry_assignment",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortalUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("google_subject", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("hosted_domain", models.CharField(max_length=253, null=True)),
                ("verified_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("disabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "stewardship_portal_user",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="appliedconfigurationversion",
            name="configuration_validation_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "validation_schema__in",
                        ["parish-integrations-v1", "foundation-policy-v2"],
                    )
                ),
                name="configuration_validation_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        ["parish-integrations-patch-v1", "foundation-policy-patch-v2"],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.AddField(
            model_name="addressrule",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddField(
            model_name="addressrolegrant",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grants",
                to="stewardship_accounts.addressrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignmentoverlay",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_accounts_assignmentoverlay_positive_version",
            ),
        ),
        migrations.AddField(
            model_name="domainrule",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddField(
            model_name="ministryassignment",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="portaluser",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_accounts_portaluser_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="addressrule",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"), name="addressrule_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressrule",
            constraint=models.UniqueConstraint(
                fields=("configuration", "email"), name="address_rule_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="addressrolegrant",
            constraint=models.UniqueConstraint(
                fields=("rule", "role"), name="address_grant_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="domainrule",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"), name="domainrule_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="domainrule",
            constraint=models.UniqueConstraint(
                fields=("configuration", "domain"), name="domain_rule_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="ministryassignment",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"), name="ministryassignment_record"
            ),
        ),
        migrations.AddConstraint(
            model_name="ministryassignment",
            constraint=models.UniqueConstraint(
                fields=("configuration", "email", "ministry_duid", "source"),
                name="ministry_assignment_identity",
            ),
        ),
    ]
