# Generated by Django 5.2.17 on 2026-09-09 21:05

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0017_policy_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyEpoch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(unique=True)),
                (
                    "activation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.configurationactivation",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_policy_epoch",
            },
        ),
        migrations.CreateModel(
            name="PolicySecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("rule_record_id", models.UUIDField()),
                ("target", models.CharField(max_length=254)),
                ("kind", models.CharField(max_length=32)),
                ("before_roles", models.JSONField()),
                ("after_roles", models.JSONField()),
                ("recipients", models.JSONField()),
                (
                    "activation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.configurationactivation",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_policy_security_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activation", "rule_record_id"),
                        name="policy_security_event_identity",
                    )
                ],
            },
        ),
    ]
