# Generated by Django 5.2.17 on 2026-09-09 21:11

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0019_policy_activation_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRevocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_admin_revocation",
            },
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_actor",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.AddField(
            model_name="configurationchangerequest",
            name="authority",
            field=models.CharField(db_default="admin", default="admin", max_length=24),
        ),
        migrations.AddField(
            model_name="configurationchangerequest",
            name="confirmed_deployment_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="configurationchangerequest",
            name="operator_name",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="configurationchangerequest",
            name="operator_reason",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="configurationchangerequest",
            name="recovery_target",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        [
                            "parish-integrations-patch-v1",
                            "foundation-policy-patch-v2",
                            "operator-recovery-patch-v1",
                        ],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor_id__isnull", False),
                        ("authority", "admin"),
                        ("confirmed_deployment_id__isnull", True),
                        ("operator_name__isnull", True),
                        ("operator_reason__isnull", True),
                        ("recovery_target__isnull", True),
                        models.Q(
                            ("request_schema", "operator-recovery-patch-v1"),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("actor_id__isnull", True),
                        ("authority", "operator_recovery"),
                        ("confirmed_deployment_id__isnull", False),
                        ("operator_name__isnull", False),
                        ("operator_reason__isnull", False),
                        ("recovery_target__isnull", False),
                        ("request_schema", "operator-recovery-patch-v1"),
                    ),
                    _connector="OR",
                ),
                name="config_request_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("authority", "operator_recovery")),
                fields=("request_key",),
                name="operator_recovery_operation",
            ),
        ),
        migrations.AddField(
            model_name="adminrevocation",
            name="activation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.configurationactivation",
            ),
        ),
    ]
