# Generated by Django 5.2.17 on 2026-09-10 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0021_operator_recovery_guards"),
        ("stewardship_campaigns", "__first__"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appliedconfigurationversion",
            name="configuration_validation_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_actor",
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="current_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "validation_schema__in",
                        [
                            "parish-integrations-v1",
                            "foundation-policy-v2",
                            "campaign-foundation-v3",
                        ],
                    )
                ),
                name="configuration_validation_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        [
                            "parish-integrations-patch-v1",
                            "foundation-policy-patch-v2",
                            "operator-recovery-patch-v1",
                            "operator-recovery-patch-v2",
                            "campaign-foundation-patch-v3",
                        ],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor_id__isnull", False),
                        ("authority", "admin"),
                        ("confirmed_deployment_id__isnull", True),
                        ("operator_name__isnull", True),
                        ("operator_reason__isnull", True),
                        ("recovery_target__isnull", True),
                        models.Q(
                            (
                                "request_schema__in",
                                [
                                    "operator-recovery-patch-v1",
                                    "operator-recovery-patch-v2",
                                ],
                            ),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("actor_id__isnull", True),
                        ("authority", "operator_recovery"),
                        ("confirmed_deployment_id__isnull", False),
                        ("operator_name__isnull", False),
                        ("operator_reason__isnull", False),
                        ("recovery_target__isnull", False),
                        (
                            "request_schema__in",
                            [
                                "operator-recovery-patch-v1",
                                "operator-recovery-patch-v2",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="config_request_actor",
            ),
        ),
    ]
