# Generated by Django 5.2.17 on 2026-09-10 10:11

from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship_accounts",
            "0022_remove_appliedconfigurationversion_configuration_validation_schema_and_more",
        ),
        ("stewardship_campaigns", "0002_campaign_guards"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="systemconfiguration",
            name="system_testing_only",
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="configuration_sequence",
            field=models.PositiveBigIntegerField(default=1, db_default=1),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="restore_activated_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="restore_backup_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="restore_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="systemconfiguration",
            name="restore_released_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="systemconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["testing", "production"])),
                name="system_known_mode",
            ),
        ),
    ]
