# Generated by Django 5.2.17 on 2026-09-10 15:45

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0023_phase1a_runtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("kind", models.CharField(max_length=32)),
                ("window", models.PositiveBigIntegerField()),
                ("level", models.CharField(max_length=16)),
                ("attempts", models.PositiveIntegerField()),
                ("sources", models.PositiveIntegerField()),
                ("identities", models.PositiveIntegerField()),
                ("candidates", models.PositiveIntegerField()),
                (
                    "resolved_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("notification_pending", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "stewardship_auth_incident",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_authenticationincident_positive_version",
                    ),
                    models.UniqueConstraint(
                        fields=("kind", "window"), name="auth_incident_window"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ["limiter_unavailable", "admin_abuse", "family_abuse"],
                            )
                        ),
                        name="auth_incident_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("level__in", ["WARNING", "CRITICAL"])),
                        name="auth_incident_level",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("kind", "limiter_unavailable"),
                            ("resolved_at__isnull", True),
                        ),
                        fields=("kind",),
                        name="auth_single_limiter_outage",
                    ),
                ],
            },
        ),
    ]
