# Generated by Django 5.2.17 on 2026-09-10 15:49

from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0024_authenticationincident"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthStateConsumption",
            fields=[
                (
                    "fingerprint",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "expires_at",
                    parishkit.stewardship.storage.UTCDateTimeField(db_index=True),
                ),
            ],
            options={
                "db_table": "stewardship_oauth_consumption",
            },
        ),
    ]
