# Generated by Django 5.2.17 on 2026-09-10 17:35

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0026_auth_incident_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="LimiterStoreHealth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("namespace_fingerprint", models.CharField(max_length=64, unique=True)),
                ("run_id", models.CharField(max_length=40)),
                ("marker", models.UUIDField()),
                ("evicted_keys", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "stewardship_limiter_health",
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="authenticationincident",
            name="auth_incident_kind",
        ),
        migrations.AddConstraint(
            model_name="authenticationincident",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        [
                            "limiter_unavailable",
                            "limiter_state_lost",
                            "admin_abuse",
                            "family_abuse",
                        ],
                    )
                ),
                name="auth_incident_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="limiterstorehealth",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_accounts_limiterstorehealth_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="limiterstorehealth",
            constraint=models.CheckConstraint(
                condition=models.Q(("namespace_fingerprint__regex", "^[0-9a-f]{64}$")),
                name="limiter_health_namespace",
            ),
        ),
        migrations.AddConstraint(
            model_name="limiterstorehealth",
            constraint=models.CheckConstraint(
                condition=models.Q(("run_id__regex", "^[0-9a-f]{40}$")),
                name="limiter_health_run_id",
            ),
        ),
    ]
