# Generated by Django 5.2.17 on 2026-09-10 18:16

import django.db.models.deletion
from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0028_limiter_health_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="SealedCredentialStaging",
            fields=[
                ("reference", models.UUIDField(primary_key=True, serialize=False)),
                ("target", models.CharField(max_length=32)),
                ("ciphertext", models.TextField(null=True)),
                ("fingerprint", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "stewardship_sealed_credential_staging",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(fingerprint__regex=r"^[0-9a-f]{64}$"),
                        name="sealed_staging_fingerprint",
                    )
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="secretreplacementrequest",
            name="secret_one_pending_target",
        ),
        migrations.RemoveConstraint(
            model_name="secretreplacementrequest",
            name="secret_known_state",
        ),
        migrations.RemoveConstraint(
            model_name="secretreplacementrequest",
            name="secret_cleanup_shape",
        ),
        migrations.RemoveConstraint(
            model_name="secretrequestcheckpoint",
            name="secret_checkpoint_state",
        ),
        migrations.AddField(
            model_name="secretreplacementrequest",
            name="acknowledged_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secretreplacementrequest",
            name="installed_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="secretreplacementrequest",
            name="required_consumers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="secretreplacementrequest",
            name="resulting_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "staged",
                            "testing",
                            "installing",
                            "awaiting_ack",
                            "cleanup_pending",
                        ),
                    )
                ),
                fields=("target",),
                name="secret_one_pending_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "staged",
                            "testing",
                            "installing",
                            "awaiting_ack",
                            "cleanup_pending",
                            "cancelled",
                            "expired",
                            "failed",
                            "applied",
                        ),
                    )
                ),
                name="secret_known_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("cleanup_reason", ""),
                        ("scrubbed_at__isnull", True),
                        (
                            "state__in",
                            ["staged", "testing", "installing", "awaiting_ack"],
                        ),
                    ),
                    models.Q(
                        (
                            "cleanup_reason__in",
                            ["cancelled", "expired", "failed", "applied"],
                        ),
                        ("scrubbed_at__isnull", True),
                        ("state", "cleanup_pending"),
                    ),
                    models.Q(
                        ("cleanup_reason", models.F("state")),
                        ("scrubbed_at__isnull", False),
                        ("state__in", ["cancelled", "expired", "failed", "applied"]),
                        ("scrubbed_at__gte", models.F("created_at")),
                    ),
                    _connector="OR",
                ),
                name="secret_cleanup_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resulting_fingerprint__isnull", True),
                    ("resulting_fingerprint__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="secret_result_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state__in", ["installing", "awaiting_ack", "applied"]),
                        _negated=True,
                    ),
                    ("resulting_fingerprint__isnull", False),
                    _connector="OR",
                ),
                name="secret_install_has_fingerprint",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["awaiting_ack", "applied"]), _negated=True),
                    ("installed_at__isnull", False),
                    _connector="OR",
                ),
                name="secret_installed_has_instant",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretreplacementrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "applied"), _negated=True),
                    ("acknowledged_at__isnull", False),
                    _connector="OR",
                ),
                name="secret_applied_has_ack",
            ),
        ),
        migrations.AddConstraint(
            model_name="secretrequestcheckpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "staged",
                            "testing",
                            "installing",
                            "awaiting_ack",
                            "cleanup_pending",
                            "cancelled",
                            "expired",
                            "failed",
                            "applied",
                        ),
                    )
                ),
                name="secret_checkpoint_state",
            ),
        ),
        migrations.AddField(
            model_name="sealedcredentialstaging",
            name="request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.secretreplacementrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="sealedcredentialstaging",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target__in",
                        (
                            "django_signing",
                            "general_encryption",
                            "family_code_mac",
                            "token_public",
                            "token_private",
                            "google_oauth",
                            "google_workspace",
                            "parishsoft",
                            "slack",
                            "backup_target",
                            "backup_data",
                            "metrics",
                        ),
                    )
                ),
                name="sealed_staging_target",
            ),
        ),
    ]
