# Generated by Django 5.2.17 on 2026-09-10 18:17

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0029_sealedcredentialstaging_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialConsumerAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("consumer", models.CharField(max_length=32)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.secretreplacementrequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_credential_consumer_ack",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "consumer"),
                        name="credential_ack_consumer_once",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fingerprint__regex", "^[0-9a-f]{64}$")),
                        name="credential_ack_fingerprint",
                    ),
                ],
            },
        ),
    ]
