# Generated by Django 5.2.17 on 2026-09-11 00:18

from django.db import migrations, models


def change_policy_predicates(editor, *, forward):
    """Extend exact retained predicates without rewriting their other checks."""
    for name, prefix, negation in (
        ("stewardship_policy_projection_v1", "version", ""),
        ("stewardship_policy_complete_v1", "NEW", "NOT "),
    ):
        old = (
            f"{prefix}.validation_schema {negation}IN "
            "('foundation-policy-v2', 'campaign-foundation-v3')"
        )
        new = old[:-1] + ", 'bootstrap-policy-v1')"
        if not forward:
            old, new = new, old
        with editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT pg_get_functiondef(%s::regprocedure)",
                ["public." + name + "()"],
            )
            definition = cursor.fetchone()[0]
        if definition.count(old) != 1:
            raise RuntimeError("Unexpected bootstrap policy migration predecessor.")
        editor.execute(definition.replace(old, new), params=None)


def change_bootstrap_audit(editor, *, forward):
    """Minimal authority is deployment-owned until an actual parish is configured.

    Missing projections for every complete historical schema still fail closed.
    The existing audit migration is an ancestor through accounts 0019, so this
    adaptation does not assume optional later audit-context migrations exist.
    """
    old = """IF NOT FOUND THEN
                RAISE EXCEPTION 'Audit Parish projection is missing'"""
    new = """IF NOT FOUND AND NOT EXISTS (
            SELECT 1 FROM public.stewardship_configuration_version v
            WHERE v.id=configuration AND v.validation_schema='bootstrap-policy-v1'
        ) THEN
                RAISE EXCEPTION 'Audit Parish projection is missing'"""
    if not forward:
        old, new = new, old
    with editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT pg_get_functiondef('public.stewardship_audit_ownership_v1()'"
            "::regprocedure)"
        )
        definition = cursor.fetchone()[0]
    if definition.count(old) != 1:
        raise RuntimeError("Unexpected bootstrap audit migration predecessor.")
    editor.execute(definition.replace(old, new), params=None)


def forward(apps, editor):
    """Admit the minimal schema only after installing its exact SQL projection rules."""
    change_policy_predicates(editor, forward=True)
    change_bootstrap_audit(editor, forward=True)
    editor.execute("""
CREATE FUNCTION public.stewardship_bootstrap_shape_v1()
RETURNS trigger LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE
    sections jsonb;
    rules jsonb;
    item jsonb;
    vals jsonb;
BEGIN
    IF NEW.validation_schema <> 'bootstrap-policy-v1' THEN RETURN NEW; END IF;
    sections := NEW.canonical_document->'sections';
    rules := sections->'login_rules';
    IF jsonb_typeof(rules) IS DISTINCT FROM 'array'
       OR sections IS DISTINCT FROM jsonb_build_object('login_rules', rules) THEN
        RAISE EXCEPTION 'Invalid bootstrap configuration shape' USING ERRCODE='23514';
    END IF;
    IF jsonb_array_length(rules) < 1
       OR (NEW.predecessor_id IS NULL AND jsonb_array_length(rules) <> 1)
       OR (NEW.predecessor_id IS NOT NULL AND NOT EXISTS (
           SELECT 1 FROM public.stewardship_configuration_version
           WHERE id=NEW.predecessor_id AND validation_schema='bootstrap-policy-v1'
       )) THEN
        RAISE EXCEPTION 'Invalid bootstrap configuration ancestry'
            USING ERRCODE='23514';
    END IF;
    FOR item IN SELECT value FROM jsonb_array_elements(rules) LOOP
        vals := item->'values';
        IF vals->>'kind' IS DISTINCT FROM 'address'
           OR vals->'roles' IS DISTINCT FROM '["administrator"]'::jsonb
           OR vals->>'creation_origin' IS DISTINCT FROM 'manual'
           OR jsonb_typeof(vals->'grants'->'administrator'->'manual')
                IS DISTINCT FROM 'string'
           OR vals->'grants' IS DISTINCT FROM jsonb_build_object(
                'administrator', jsonb_build_object(
                    'manual', vals->'grants'->'administrator'->'manual')) THEN
            RAISE EXCEPTION 'Bootstrap requires exact manual Admin grants'
                USING ERRCODE='23514';
        END IF;
    END LOOP;
    RETURN NEW;
END;
$$;
CREATE TRIGGER stewardship_bootstrap_shape_v1
BEFORE INSERT ON public.stewardship_configuration_version
FOR EACH ROW EXECUTE FUNCTION public.stewardship_bootstrap_shape_v1();

CREATE FUNCTION public.stewardship_bootstrap_projection_v1()
RETURNS trigger LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.stewardship_configuration_version
               WHERE id=NEW.configuration_id
                 AND validation_schema='bootstrap-policy-v1') THEN
        RAISE EXCEPTION 'Bootstrap forbids unrelated projections' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER stewardship_bootstrap_projection_v1
BEFORE INSERT ON public.stewardship_parish
FOR EACH ROW EXECUTE FUNCTION public.stewardship_bootstrap_projection_v1();
CREATE TRIGGER stewardship_bootstrap_projection_v1
BEFORE INSERT ON public.stewardship_applied_integration
FOR EACH ROW EXECUTE FUNCTION public.stewardship_bootstrap_projection_v1();
    """)


def backward(apps, editor):
    """Refuse populated downgrade before removing policy or schema protections."""
    editor.execute("""
        LOCK TABLE public.stewardship_configuration_version IN ACCESS EXCLUSIVE MODE;
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM public.stewardship_configuration_version
                       WHERE validation_schema='bootstrap-policy-v1') THEN
                RAISE EXCEPTION 'Bootstrap history prevents schema downgrade'
                    USING ERRCODE='23514';
            END IF;
        END $$;
    """)
    change_policy_predicates(editor, forward=False)
    change_bootstrap_audit(editor, forward=False)
    editor.execute("""
DROP TRIGGER stewardship_bootstrap_projection_v1 ON public.stewardship_parish;
DROP TRIGGER stewardship_bootstrap_projection_v1
    ON public.stewardship_applied_integration;
DROP FUNCTION public.stewardship_bootstrap_projection_v1();
DROP TRIGGER stewardship_bootstrap_shape_v1 ON public.stewardship_configuration_version;
DROP FUNCTION public.stewardship_bootstrap_shape_v1();
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0033_trusted_trigger_paths"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appliedconfigurationversion",
            name="configuration_validation_schema",
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "validation_schema__in",
                        [
                            "parish-integrations-v1",
                            "foundation-policy-v2",
                            "campaign-foundation-v3",
                            "bootstrap-policy-v1",
                        ],
                    )
                ),
                name="configuration_validation_schema",
            ),
        ),
        migrations.RunPython(forward, backward),
    ]
