# Generated by Django 5.2.17 on 2026-09-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0034_bootstrap_configuration_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_actor",
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        [
                            "parish-integrations-patch-v1",
                            "foundation-policy-patch-v2",
                            "operator-recovery-patch-v1",
                            "operator-recovery-patch-v2",
                            "operator-recovery-bootstrap-v1",
                            "campaign-foundation-patch-v3",
                        ],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor_id__isnull", False),
                        ("authority", "admin"),
                        ("confirmed_deployment_id__isnull", True),
                        ("operator_name__isnull", True),
                        ("operator_reason__isnull", True),
                        ("recovery_target__isnull", True),
                        models.Q(
                            (
                                "request_schema__in",
                                [
                                    "operator-recovery-patch-v1",
                                    "operator-recovery-patch-v2",
                                    "operator-recovery-bootstrap-v1",
                                ],
                            ),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("actor_id__isnull", True),
                        ("authority", "operator_recovery"),
                        ("confirmed_deployment_id__isnull", False),
                        ("operator_name__isnull", False),
                        ("operator_reason__isnull", False),
                        ("recovery_target__isnull", False),
                        (
                            "request_schema__in",
                            [
                                "operator-recovery-patch-v1",
                                "operator-recovery-patch-v2",
                                "operator-recovery-bootstrap-v1",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="config_request_actor",
            ),
        ),
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="""
LOCK TABLE public.stewardship_config_request IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM public.stewardship_config_request
               WHERE request_schema='operator-recovery-bootstrap-v1') THEN
        RAISE EXCEPTION 'Bootstrap recovery history prevents downgrade'
            USING ERRCODE='23514';
    END IF;
END $$;
            """,
        ),
    ]
