# Generated by Django 5.2.17 on 2026-09-08 18:53

import uuid

import django.utils.timezone
from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("subject_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "stewardship_audit_event",
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="audit_event_time"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("event_type__regex", "^[a-z][a-z0-9_]{0,63}$")
                        ),
                        name="audit_event_type_identifier",
                    )
                ],
            },
        ),
    ]
