# Generated by Django 5.2.17 on 2026-09-08 20:20

import django.db.models.functions.datetime
from django.db import migrations

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_audit", "0003_operation_correlation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="created_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(
                db_default=django.db.models.functions.datetime.Now(), editable=False
            ),
        ),
    ]
