# Generated by Django 5.2.17 on 2026-09-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_audit", "0004_alter_auditevent_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="subject_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
