# Generated by Django 5.2.17 on 2026-09-10 17:02

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_audit", "0006_parish_ownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("actor_kind", models.CharField(max_length=16)),
                ("schema", models.CharField(max_length=16)),
                ("context", models.JSONField(default=dict)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_audit.auditevent",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_audit_context",
            },
        ),
        migrations.CreateModel(
            name="OperationalLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("level", models.CharField(max_length=8)),
                ("event", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=16)),
                ("context", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "stewardship_operational_log",
                "indexes": [
                    models.Index(
                        fields=["level", "created_at"], name="operational_level_time"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "level__in",
                                ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
                            )
                        ),
                        name="operational_log_level",
                    )
                ],
            },
        ),
    ]
