# Generated by Django 5.2.17 on 2026-09-14 03:54

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stewardship_responses", "0001_initial"),
        ("stewardship_source", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="MinistryRequest",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("entity_kind", models.CharField(max_length=20)),
                        ("entity_key", models.CharField(max_length=36)),
                        ("ministry_duid", models.PositiveIntegerField()),
                        ("action", models.CharField(max_length=5)),
                        ("state", models.CharField(default="new", max_length=20)),
                        ("outcome", models.CharField(max_length=20, null=True)),
                        (
                            "resolved_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "resolution_source",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_source.sourcesnapshot",
                            ),
                        ),
                        (
                            "submission",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.submission",
                            ),
                        ),
                        (
                            "superseded_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_workflows.ministryrequest",
                            ),
                        ),
                        ("assignee_id", models.UUIDField(null=True)),
                    ],
                    options={
                        "db_table": "stewardship_ministry_request",
                        "abstract": False,
                        "indexes": [
                            models.Index(
                                fields=["ministry_duid", "state"],
                                name="ministry_request_queue",
                            )
                        ],
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(("version__gte", 1)),
                                name="stewardship_workflows_ministryrequest_positive_version",
                            ),
                            models.UniqueConstraint(
                                fields=(
                                    "submission",
                                    "entity_kind",
                                    "entity_key",
                                    "ministry_duid",
                                ),
                                name="ministry_request_identity",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("entity_kind__in", ["member", "proposed_member"]),
                                    models.Q(("entity_key", ""), _negated=True),
                                    ("ministry_duid__gt", 0),
                                    ("ministry_duid__lt", 2147483648),
                                ),
                                name="ministry_request_entity",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("action__in", ["join", "leave"]),
                                    models.Q(
                                        ("action", "leave"),
                                        ("entity_kind", "proposed_member"),
                                        _negated=True,
                                    ),
                                ),
                                name="ministry_request_action",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    (
                                        "state__in",
                                        [
                                            "new",
                                            "assigned",
                                            "in_progress",
                                            "resolved",
                                            "closed_no_response",
                                            "cancelled",
                                            "superseded",
                                        ],
                                    )
                                ),
                                name="ministry_request_state",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        (
                                            "state__in",
                                            ["resolved", "closed_no_response"],
                                        ),
                                        ("outcome__isnull", False),
                                        ("resolved_at__isnull", False),
                                        (
                                            "outcome__in",
                                            [
                                                "joined",
                                                "leave_confirmed",
                                                "declined",
                                                "no_response",
                                                "duplicate",
                                                "other",
                                            ],
                                        ),
                                    ),
                                    models.Q(
                                        models.Q(
                                            (
                                                "state__in",
                                                ["resolved", "closed_no_response"],
                                            ),
                                            _negated=True,
                                        ),
                                        ("outcome__isnull", True),
                                        ("resolution_source__isnull", True),
                                        ("resolved_at__isnull", True),
                                    ),
                                    _connector="OR",
                                ),
                                name="ministry_request_outcome",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        ("state", "superseded"),
                                        ("superseded_by__isnull", False),
                                    ),
                                    models.Q(
                                        models.Q(
                                            ("state", "superseded"), _negated=True
                                        ),
                                        ("superseded_by__isnull", True),
                                    ),
                                    _connector="OR",
                                ),
                                name="ministry_request_successor",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("superseded_by_id", models.F("id")), _negated=True
                                ),
                                name="ministry_request_not_own_next",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        models.Q(("state", "new"), _negated=True),
                                        ("assignee_id__isnull", True),
                                        _connector="OR",
                                    ),
                                    models.Q(
                                        models.Q(("state", "assigned"), _negated=True),
                                        ("assignee_id__isnull", False),
                                        _connector="OR",
                                    ),
                                ),
                                name="ministry_request_assignment",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="MinistryWorkflowRevision",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("expected_version", models.PositiveBigIntegerField()),
                        ("request_key", models.UUIDField()),
                        ("assignee_id", models.UUIDField(null=True)),
                        ("state", models.CharField(max_length=20)),
                        ("outcome", models.CharField(max_length=20, null=True)),
                        ("notes", models.TextField(blank=True, default="")),
                        (
                            "contact_channel",
                            models.CharField(max_length=10, null=True),
                        ),
                        (
                            "contact_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        ("contact_notes", models.TextField(blank=True, default="")),
                        (
                            "request",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="revisions",
                                to="stewardship_workflows.ministryrequest",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_ministry_revision",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("request", "expected_version"),
                                name="ministry_revision_version",
                            ),
                            models.UniqueConstraint(
                                fields=("actor_id", "request_key"),
                                name="ministry_revision_replay",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("actor_id__isnull", False),
                                    ("expected_version__gte", 1),
                                ),
                                name="ministry_revision_identity",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        models.Q(
                                            ("outcome__isnull", True),
                                            (
                                                "state__in",
                                                ["new", "assigned", "in_progress"],
                                            ),
                                        ),
                                        models.Q(
                                            (
                                                "outcome__in",
                                                [
                                                    "joined",
                                                    "leave_confirmed",
                                                    "declined",
                                                    "duplicate",
                                                    "other",
                                                ],
                                            ),
                                            ("state", "resolved"),
                                        ),
                                        models.Q(
                                            ("outcome", "no_response"),
                                            ("state", "closed_no_response"),
                                        ),
                                        _connector="OR",
                                    ),
                                    models.Q(
                                        models.Q(("outcome", "other"), _negated=True),
                                        models.Q(("notes", ""), _negated=True),
                                        _connector="OR",
                                    ),
                                ),
                                name="ministry_revision_outcome",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        models.Q(("state", "new"), _negated=True),
                                        ("assignee_id__isnull", True),
                                        _connector="OR",
                                    ),
                                    models.Q(
                                        models.Q(("state", "assigned"), _negated=True),
                                        ("assignee_id__isnull", False),
                                        _connector="OR",
                                    ),
                                ),
                                name="ministry_revision_assignment",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    models.Q(
                                        ("contact_at__isnull", True),
                                        ("contact_channel__isnull", True),
                                        ("contact_notes", ""),
                                    ),
                                    models.Q(
                                        ("contact_at__isnull", False),
                                        (
                                            "contact_channel__in",
                                            ["email", "phone", "in_person", "other"],
                                        ),
                                    ),
                                    _connector="OR",
                                ),
                                name="ministry_revision_contact",
                            ),
                        ],
                    },
                ),
            ]
        )
    ]
