# Generated by Django 5.2.17 on 2026-09-14 21:51

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    # Baseline SQL owns creation; this step only resolves cross-app model state.
    initial = True

    dependencies = [
        ("stewardship_accounts", "0003_initial"),
        ("stewardship_campaigns", "0001_initial"),
        ("stewardship_jobs", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="DeliveryResolution",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, null=True, editable=False),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                default=parishkit.stewardship.observability.current_correlation,
                                db_index=True,
                                editable=False,
                            ),
                        ),
                        ("message_id", models.UUIDField()),
                        ("expected_version", models.PositiveBigIntegerField()),
                        ("action", models.CharField(max_length=16)),
                        ("evidence_note", models.CharField(max_length=2000)),
                        ("duplicate_acknowledged", models.BooleanField(default=False)),
                        ("previous_task_id", models.UUIDField(null=True)),
                        ("retry_task_id", models.UUIDField(null=True)),
                        ("preparation", models.JSONField(null=True, default=None)),
                    ],
                    options={
                        "db_table": "stewardship_delivery_resolution",
                        "indexes": [
                            models.Index(
                                fields=["message_id", "created_at"],
                                name="delivery_resolution_history",
                            )
                        ],
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(
                                    action__in=(
                                        "note",
                                        "accept",
                                        "resend",
                                        "retry_failed",
                                        "retry_unsent",
                                    )
                                ),
                                name="delivery_resolution_action",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(expected_version__gt=0),
                                name="delivery_resolution_version",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(preparation__isnull=True),
                                name="delivery_resolution_scrubbed",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="FamilyMailPreparation",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, null=True, editable=False),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                default=parishkit.stewardship.observability.current_correlation,
                                db_index=True,
                                editable=False,
                            ),
                        ),
                        ("occurrence_id", models.UUIDField()),
                        ("task_id", models.UUIDField(unique=True)),
                        ("mode", models.CharField(max_length=16)),
                        ("rehearsal_epoch_id", models.UUIDField(null=True)),
                    ],
                    options={
                        "db_table": "stewardship_family_mail_preparation",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("occurrence_id", "rehearsal_epoch_id"),
                                nulls_distinct=False,
                                name="family_mail_preparation_scope",
                            ),
                            models.CheckConstraint(
                                condition=(
                                    models.Q(
                                        mode="production",
                                        rehearsal_epoch_id__isnull=True,
                                    )
                                    | models.Q(
                                        mode="testing", rehearsal_epoch_id__isnull=False
                                    )
                                ),
                                name="family_mail_preparation_namespace",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="RecipientRefusal",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("family_id", models.UUIDField()),
                        ("organization_id", models.PositiveBigIntegerField()),
                        ("family_duid", models.PositiveBigIntegerField()),
                        ("event_id", models.UUIDField()),
                        ("address", models.CharField(max_length=254)),
                    ],
                    options={
                        "db_table": "stewardship_recipient_refusal",
                        "indexes": [
                            models.Index(
                                fields=["family_id"], name="recipient_refusal_family"
                            ),
                            models.Index(
                                fields=["organization_id", "family_duid"],
                                name="recipient_refusal_identity",
                            ),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=["event_id", "address"],
                                name="recipient_refusal_event_address",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(organization_id__gt=0)
                                & models.Q(family_duid__gt=0),
                                name="recipient_refusal_identity_positive",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="RecipientRefusalResolution",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("refusal_id", models.UUIDField(unique=True)),
                        ("source_snapshot_id", models.UUIDField()),
                        ("source_generation", models.PositiveBigIntegerField()),
                        (
                            "evidence_note",
                            models.CharField(max_length=2000, blank=True, default=""),
                        ),
                        (
                            "reason",
                            models.CharField(default="source_changed", max_length=32),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_recipient_resolution",
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(
                                    reason="source_changed", evidence_note=""
                                )
                                | (
                                    models.Q(
                                        reason="verified_admin", actor_id__isnull=False
                                    )
                                    & ~models.Q(evidence_note="")
                                ),
                                name="recipient_resolution_reason",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(source_generation__gt=0),
                                name="recipient_resolution_generation",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="DeliveryPauseHold",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("pause_version", models.PositiveBigIntegerField()),
                        (
                            "campaign",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.campaign",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_delivery_pause_hold",
                    },
                ),
                migrations.CreateModel(
                    name="OutboxMessage",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("command_id", models.UUIDField()),
                        ("command_digest", models.CharField(max_length=64)),
                        ("action", models.CharField(max_length=24)),
                        (
                            "provider_key_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "provider_message_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "evidence_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "evidence_note",
                            models.CharField(blank=True, max_length=2000),
                        ),
                        ("reason", models.CharField(blank=True, max_length=64)),
                        ("scope_id", models.UUIDField()),
                        ("semantic_key", models.UUIDField()),
                        ("mode", models.CharField(max_length=16)),
                        ("routing", models.CharField(max_length=24)),
                        ("purpose", models.CharField(max_length=24)),
                        (
                            "credential_namespace",
                            models.CharField(default="none", max_length=16),
                        ),
                        ("rehearsal_epoch_id", models.UUIDField(null=True)),
                        ("token_generation_id", models.UUIDField(null=True)),
                        ("credential_epoch_id", models.UUIDField(null=True)),
                        ("sealed_substitutions", models.TextField(null=True)),
                        ("sealed_key_id", models.CharField(max_length=48, null=True)),
                        (
                            "state",
                            models.CharField(
                                db_default="pending", default="pending", max_length=24
                            ),
                        ),
                        (
                            "attempt",
                            models.PositiveBigIntegerField(db_default=0, default=0),
                        ),
                        (
                            "not_before",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now()
                            ),
                        ),
                        ("task_fence", models.PositiveBigIntegerField(null=True)),
                        ("worker_id", models.UUIDField(null=True)),
                        (
                            "submitted_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "provider_deadline",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "finished_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        ("pause_version", models.PositiveBigIntegerField(null=True)),
                        (
                            "campaign",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.campaign",
                            ),
                        ),
                        (
                            "family",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.familycampaign",
                            ),
                        ),
                        (
                            "pause_hold",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_jobs.deliverypausehold",
                            ),
                        ),
                        (
                            "run",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="outbox_attempts",
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                        (
                            "task",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_outbox_message",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="OutboxRender",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("sender", models.EmailField(max_length=254)),
                        ("reply_to", models.EmailField(max_length=254)),
                        ("intended_recipients", models.JSONField()),
                        ("routed_recipients", models.JSONField()),
                        ("subject", models.CharField(max_length=254)),
                        ("html", models.TextField()),
                        ("text", models.TextField()),
                        ("payload_digest", models.CharField(max_length=64)),
                        (
                            "configuration",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_accounts.appliedconfigurationversion",
                            ),
                        ),
                        (
                            "message",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="renders",
                                to="stewardship_jobs.outboxmessage",
                            ),
                        ),
                        (
                            "template",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_accounts.contentversion",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_outbox_render",
                    },
                ),
                migrations.AddField(
                    model_name="outboxmessage",
                    name="render",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stewardship_jobs.outboxrender",
                    ),
                ),
                migrations.CreateModel(
                    name="OutboxEvent",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("command_id", models.UUIDField()),
                        ("command_digest", models.CharField(max_length=64)),
                        ("action", models.CharField(max_length=24)),
                        (
                            "provider_key_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "provider_message_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "evidence_digest",
                            models.CharField(blank=True, max_length=64),
                        ),
                        (
                            "evidence_note",
                            models.CharField(blank=True, max_length=2000),
                        ),
                        ("reason", models.CharField(blank=True, max_length=64)),
                        ("version", models.PositiveBigIntegerField()),
                        ("previous_state", models.CharField(blank=True, max_length=24)),
                        ("state", models.CharField(max_length=24)),
                        ("attempt", models.PositiveBigIntegerField()),
                        ("task_fence", models.PositiveBigIntegerField(null=True)),
                        ("worker_id", models.UUIDField(null=True)),
                        (
                            "not_before",
                            parishkit.stewardship.storage.UTCDateTimeField(),
                        ),
                        (
                            "submitted_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "provider_deadline",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "finished_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "run",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                        (
                            "message",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="events",
                                to="stewardship_jobs.outboxmessage",
                            ),
                        ),
                        (
                            "render",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_jobs.outboxrender",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_outbox_event",
                    },
                ),
                migrations.AddConstraint(
                    model_name="deliverypausehold",
                    constraint=models.UniqueConstraint(
                        fields=("campaign", "pause_version"),
                        name="delivery_pause_identity",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="deliverypausehold",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("pause_version__gte", 1)),
                        name="delivery_pause_positive",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxrender",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("payload_digest__regex", "^[0-9a-f]{64}$")),
                        name="outbox_render_digest",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxrender",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("subject", ""), _negated=True),
                        name="outbox_render_subject",
                    ),
                ),
                migrations.AddIndex(
                    model_name="outboxmessage",
                    index=models.Index(
                        fields=["state", "not_before"], name="outbox_due"
                    ),
                ),
                migrations.AddIndex(
                    model_name="outboxmessage",
                    index=models.Index(
                        fields=["campaign", "state"], name="outbox_campaign_state"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_jobs_outboxmessage_positive_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.UniqueConstraint(
                        fields=("scope_id", "mode", "semantic_key"),
                        name="outbox_semantic_key",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "pending",
                                    "submitting",
                                    "retry_wait",
                                    "delivery_unknown",
                                    "delivered",
                                    "permanent_failure",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="outbox_known_state",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                (
                                    "created",
                                    "prepared",
                                    "hold",
                                    "release_hold",
                                    "submit",
                                    "accept",
                                    "retry_unaccepted",
                                    "fail_unaccepted",
                                    "mark_unknown",
                                    "cancel_unsent",
                                    "retry_failed",
                                    "authorize_resend",
                                    "retry_idempotent",
                                ),
                            )
                        ),
                        name="outbox_action",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "purpose__in",
                                (
                                    "initial",
                                    "reminder",
                                    "receipt",
                                    "daily_digest",
                                    "weekly_digest",
                                    "operational",
                                ),
                            )
                        ),
                        name="outbox_purpose",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("mode__in", ["testing", "production"])),
                        name="outbox_mode",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("family", None),
                                ("purpose", "operational"),
                                ("routing", "operational"),
                            ),
                            models.Q(
                                models.Q(("purpose", "operational"), _negated=True),
                                ("campaign__isnull", False),
                                models.Q(
                                    models.Q(
                                        ("mode", "testing"),
                                        ("routing", "testing_override"),
                                    ),
                                    models.Q(
                                        ("mode", "production"),
                                        ("routing", "production"),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_routing",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("family__isnull", False),
                                ("purpose__in", ["initial", "reminder", "receipt"]),
                            ),
                            models.Q(
                                ("family", None),
                                (
                                    "purpose__in",
                                    ["daily_digest", "weekly_digest", "operational"],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_family_purpose",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("credential_epoch_id", None),
                                ("credential_namespace", "none"),
                                ("rehearsal_epoch_id", None),
                                ("sealed_key_id", None),
                                ("sealed_substitutions", None),
                                ("token_generation_id", None),
                            ),
                            models.Q(
                                ("family__isnull", False),
                                models.Q(
                                    models.Q(
                                        ("credential_epoch_id__isnull", False),
                                        ("credential_namespace", "production"),
                                        ("mode", "production"),
                                        ("rehearsal_epoch_id", None),
                                        ("token_generation_id__isnull", False),
                                    ),
                                    models.Q(
                                        ("credential_epoch_id", None),
                                        ("credential_namespace", "rehearsal"),
                                        ("mode", "testing"),
                                        ("rehearsal_epoch_id__isnull", False),
                                        ("token_generation_id", None),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_credential_namespace",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finished_at__isnull", False),
                                ("sealed_key_id", None),
                                ("sealed_substitutions", None),
                                (
                                    "state__in",
                                    ("delivered", "permanent_failure", "cancelled"),
                                ),
                            ),
                            models.Q(
                                models.Q(
                                    (
                                        "state__in",
                                        ("delivered", "permanent_failure", "cancelled"),
                                    ),
                                    _negated=True,
                                ),
                                ("finished_at", None),
                                models.Q(
                                    ("credential_namespace", "none"),
                                    models.Q(
                                        ("sealed_key_id__isnull", False),
                                        ("sealed_substitutions__isnull", False),
                                    ),
                                    _connector="OR",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_terminal_scrub",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("attempt", 0),
                                ("provider_deadline", None),
                                ("run", None),
                                ("submitted_at", None),
                                ("task_fence", None),
                                ("worker_id", None),
                            ),
                            models.Q(
                                ("attempt__gte", 1),
                                ("provider_deadline__gte", models.F("submitted_at")),
                                ("provider_deadline__isnull", False),
                                ("run__isnull", False),
                                ("submitted_at__isnull", False),
                                ("task_fence__gte", 1),
                                ("task_fence__isnull", False),
                                ("worker_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_attempt_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "state__in",
                                    [
                                        "submitting",
                                        "delivery_unknown",
                                        "delivered",
                                        "retry_wait",
                                    ],
                                ),
                                _negated=True,
                            ),
                            ("attempt__gte", 1),
                            _connector="OR",
                        ),
                        name="outbox_submitted_outcome",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxmessage",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("pause_hold", None),
                            models.Q(
                                ("campaign__isnull", False),
                                ("pause_version__gte", 1),
                                ("pause_version__isnull", False),
                                ("routing", "production"),
                                ("state__in", ["pending", "retry_wait"]),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_pause_shape",
                    ),
                ),
                migrations.AddIndex(
                    model_name="outboxevent",
                    index=models.Index(
                        fields=["message", "attempt"], name="outbox_attempt_history"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.UniqueConstraint(
                        fields=("message", "version"), name="outbox_event_version"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.UniqueConstraint(
                        fields=("message", "command_id"), name="outbox_command_once"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="outbox_event_positive",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("command_digest__regex", "^[0-9a-f]{64}$")),
                        name="outbox_command_digest",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                (
                                    "created",
                                    "prepared",
                                    "hold",
                                    "release_hold",
                                    "submit",
                                    "accept",
                                    "retry_unaccepted",
                                    "fail_unaccepted",
                                    "mark_unknown",
                                    "cancel_unsent",
                                    "retry_failed",
                                    "authorize_resend",
                                    "retry_idempotent",
                                ),
                            )
                        ),
                        name="outbox_event_action",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "pending",
                                    "submitting",
                                    "retry_wait",
                                    "delivery_unknown",
                                    "delivered",
                                    "permanent_failure",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="outbox_event_state",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "previous_state__in",
                                [
                                    "",
                                    "pending",
                                    "submitting",
                                    "retry_wait",
                                    "delivery_unknown",
                                    "delivered",
                                    "permanent_failure",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="outbox_event_previous_state",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("provider_key_digest", ""),
                                ("provider_key_digest__regex", "^[0-9a-f]{64}$"),
                                _connector="OR",
                            ),
                            models.Q(
                                ("provider_message_digest", ""),
                                ("provider_message_digest__regex", "^[0-9a-f]{64}$"),
                                _connector="OR",
                            ),
                            models.Q(
                                ("evidence_digest", ""),
                                ("evidence_digest__regex", "^[0-9a-f]{64}$"),
                                _connector="OR",
                            ),
                        ),
                        name="outbox_event_digests",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="outboxevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("reason", ""),
                            ("reason__regex", "^[a-z][a-z0-9_]{0,63}$"),
                            _connector="OR",
                        ),
                        name="outbox_event_reason",
                    ),
                ),
            ]
        )
    ]
