# Generated by Django 5.2.17 on 2026-09-13 17:31

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stewardship_accounts", "0003_initial"),
        ("stewardship_campaigns", "0001_initial"),
        ("stewardship_source", "0001_initial"),
        ("stewardship_jobs", "0002_initial_delivery"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AdditionalInformationRevision",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("expected_version", models.PositiveBigIntegerField()),
                        ("request_key", models.UUIDField()),
                        ("follow_up_needed", models.BooleanField()),
                        ("followed_up", models.BooleanField()),
                        ("confirm_clear", models.BooleanField(default=False)),
                        ("notes", models.TextField(blank=True, default="")),
                        (
                            "followed_up_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        ("followed_up_by_id", models.UUIDField(null=True)),
                        (
                            "item",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="revisions",
                                to="stewardship_responses.additionalinformationitem",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_information_revision",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("item", "expected_version"),
                                name="information_revision_version",
                            ),
                            models.UniqueConstraint(
                                fields=("actor_id", "request_key"),
                                name="information_revision_replay",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    actor_id__isnull=False, expected_version__gte=1
                                ),
                                name="information_revision_identity",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    followed_up=True,
                                    followed_up_at__isnull=False,
                                    followed_up_by_id__isnull=False,
                                )
                                | models.Q(
                                    followed_up=False,
                                    followed_up_at__isnull=True,
                                    followed_up_by_id__isnull=True,
                                ),
                                name="information_revision_completion",
                            ),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="FamilyFormBaseline",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("family_session_id", models.UUIDField()),
                        ("mode", models.CharField(max_length=4)),
                        ("rehearsal_epoch_id", models.UUIDField(null=True)),
                        ("form_schema", models.CharField(max_length=48)),
                        ("projection_version", models.CharField(max_length=48)),
                        ("projection_digest", models.CharField(max_length=64)),
                        ("definition_digest", models.CharField(max_length=64)),
                        (
                            "expires_at",
                            parishkit.stewardship.storage.UTCDateTimeField(),
                        ),
                        ("state", models.CharField(default="open", max_length=12)),
                        (
                            "ended_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "configuration",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_accounts.appliedconfigurationversion",
                            ),
                        ),
                        (
                            "family",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.familycampaign",
                            ),
                        ),
                        (
                            "source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_source.sourcesnapshot",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_family_form_baseline",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="Submission",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("campaign_sequence", models.PositiveBigIntegerField()),
                        ("mode", models.CharField(max_length=4)),
                        ("rehearsal_epoch_id", models.UUIDField(null=True)),
                        ("family_version", models.PositiveBigIntegerField()),
                        (
                            "submitted_at",
                            parishkit.stewardship.storage.UTCDateTimeField(),
                        ),
                        ("submitted_on", models.DateField()),
                        ("form_schema", models.CharField(max_length=48)),
                        ("answers", models.JSONField()),
                        (
                            "annual_pledge",
                            models.DecimalField(
                                decimal_places=2, max_digits=14, null=True
                            ),
                        ),
                        (
                            "baseline",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.familyformbaseline",
                            ),
                        ),
                        (
                            "campaign",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.campaign",
                            ),
                        ),
                        (
                            "configuration",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_accounts.appliedconfigurationversion",
                            ),
                        ),
                        (
                            "family",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_campaigns.familycampaign",
                            ),
                        ),
                        (
                            "prior_submission",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.submission",
                            ),
                        ),
                        (
                            "reviewed_source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="reviewed_submissions",
                                to="stewardship_source.sourcesnapshot",
                            ),
                        ),
                        (
                            "validation_source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="validated_submissions",
                                to="stewardship_source.sourcesnapshot",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_submission",
                    },
                ),
                migrations.CreateModel(
                    name="ProposedChange",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("entity_kind", models.CharField(max_length=20)),
                        ("entity_key", models.CharField(max_length=36)),
                        ("field", models.CharField(max_length=40)),
                        ("baseline_available", models.BooleanField()),
                        ("baseline_value", models.JSONField(null=True)),
                        ("submitted_value", models.JSONField(null=True)),
                        ("current_available", models.BooleanField()),
                        ("current_value", models.JSONField(null=True)),
                        ("admin_value_set", models.BooleanField(default=False)),
                        ("admin_value", models.JSONField(null=True)),
                        ("handling", models.CharField(max_length=12)),
                        (
                            "decision",
                            models.CharField(default="unreviewed", max_length=12),
                        ),
                        (
                            "execution",
                            models.CharField(default="pending", max_length=20),
                        ),
                        (
                            "current_source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_source.sourcesnapshot",
                            ),
                        ),
                        (
                            "superseded_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.proposedchange",
                            ),
                        ),
                        (
                            "submission",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.submission",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_proposed_change",
                        "abstract": False,
                    },
                ),
                migrations.AddField(
                    model_name="familyformbaseline",
                    name="prior_submission",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="later_baselines",
                        to="stewardship_responses.submission",
                    ),
                ),
                migrations.CreateModel(
                    name="AdditionalInformationItem",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("text", models.TextField()),
                        (
                            "disposition",
                            models.CharField(
                                default="current_actionable", max_length=20
                            ),
                        ),
                        ("follow_up_needed", models.BooleanField(default=False)),
                        (
                            "followed_up_at",
                            parishkit.stewardship.storage.UTCDateTimeField(null=True),
                        ),
                        (
                            "replacement",
                            models.OneToOneField(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="replaces",
                                to="stewardship_responses.additionalinformationitem",
                            ),
                        ),
                        (
                            "submission",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.submission",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_additional_information",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="SubmissionReceiptOccurrence",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("disposition", models.CharField(max_length=28)),
                        ("preparation", models.JSONField(null=True)),
                        (
                            "outbox",
                            models.OneToOneField(
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_jobs.outboxmessage",
                            ),
                        ),
                        (
                            "submission",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_responses.submission",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_submission_receipt",
                    },
                ),
                migrations.AddIndex(
                    model_name="submission",
                    index=models.Index(
                        fields=["family", "mode", "submitted_at"],
                        name="submission_family_time",
                    ),
                ),
                migrations.AddIndex(
                    model_name="submission",
                    index=models.Index(
                        fields=["mode", "submitted_on"], name="submission_local_day"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.UniqueConstraint(
                        fields=("campaign", "mode", "campaign_sequence"),
                        name="submission_campaign_sequence",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.UniqueConstraint(
                        fields=("family", "mode", "family_version"),
                        name="submission_family_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("mode", "live"), ("rehearsal_epoch_id__isnull", True)
                            ),
                            models.Q(
                                ("mode", "test"), ("rehearsal_epoch_id__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="submission_mode_epoch",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("campaign_sequence__gt", 0),
                            ("family_version__gt", 0),
                            models.Q(("form_schema", ""), _negated=True),
                        ),
                        name="submission_version_identity",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("annual_pledge__isnull", True),
                            models.Q(
                                ("annual_pledge__gte", 0),
                                ("annual_pledge__lte", "999999999.99"),
                            ),
                            _connector="OR",
                        ),
                        name="submission_supported_pledge",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submission",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("prior_submission_id", models.F("id")), _negated=True
                        ),
                        name="submission_not_own_predecessor",
                    ),
                ),
                migrations.AddIndex(
                    model_name="proposedchange",
                    index=models.Index(
                        fields=["decision", "execution"], name="proposal_review_queue"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_responses_proposedchange_positive_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.UniqueConstraint(
                        fields=("submission", "entity_kind", "entity_key", "field"),
                        name="proposal_atomic_identity",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "entity_kind__in",
                                ["family", "member", "proposed_member"],
                            ),
                            models.Q(("entity_key", ""), _negated=True),
                            models.Q(("field", ""), _negated=True),
                        ),
                        name="proposal_entity_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("handling__in", ["api", "manual", "report-only"])
                        ),
                        name="proposal_handling",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("decision__in", ["unreviewed", "approved", "ignored"])
                        ),
                        name="proposal_decision",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "execution__in",
                                [
                                    "pending",
                                    "conflict",
                                    "queued",
                                    "published",
                                    "resolved_upstream",
                                    "resolved_external",
                                    "failed",
                                    "superseded",
                                    "cancelled",
                                ],
                            )
                        ),
                        name="proposal_execution",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("baseline_available", True),
                            ("baseline_value__isnull", True),
                            _connector="OR",
                        ),
                        name="proposal_baseline_availability",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("current_available", True),
                            ("current_value__isnull", True),
                            _connector="OR",
                        ),
                        name="proposal_current_availability",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("admin_value_set", True),
                            ("admin_value__isnull", True),
                            _connector="OR",
                        ),
                        name="proposal_admin_value_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="proposedchange",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("superseded_by_id", models.F("id")), _negated=True
                        ),
                        name="proposal_not_own_successor",
                    ),
                ),
                migrations.AddIndex(
                    model_name="familyformbaseline",
                    index=models.Index(
                        fields=["state", "expires_at"], name="family_baseline_expiry"
                    ),
                ),
                migrations.AddIndex(
                    model_name="familyformbaseline",
                    index=models.Index(
                        fields=["family_session_id", "state"],
                        name="family_baseline_session",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="familyformbaseline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_responses_familyformbaseline_positive_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="familyformbaseline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("mode", "live"), ("rehearsal_epoch_id__isnull", True)
                            ),
                            models.Q(
                                ("mode", "test"), ("rehearsal_epoch_id__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="family_baseline_mode_epoch",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="familyformbaseline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("ended_at__isnull", True), ("state", "open")),
                            models.Q(
                                ("ended_at__gte", models.F("created_at")),
                                ("ended_at__isnull", False),
                                (
                                    "state__in",
                                    ["submitted", "replaced", "cancelled", "expired"],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="family_baseline_state_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="familyformbaseline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="family_baseline_future_expiry",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="familyformbaseline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("projection_digest__regex", "^[0-9a-f]{64}$"),
                            ("definition_digest__regex", "^[0-9a-f]{64}$"),
                            models.Q(("form_schema", ""), _negated=True),
                            models.Q(("projection_version", ""), _negated=True),
                        ),
                        name="family_baseline_contract_identity",
                    ),
                ),
                migrations.AddIndex(
                    model_name="additionalinformationitem",
                    index=models.Index(
                        fields=["disposition", "created_at"],
                        name="additional_actionable_queue",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="additionalinformationitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_responses_additionalinformationitem_positive_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="additionalinformationitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("text", ""), _negated=True),
                        name="additional_nonblank_text",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="additionalinformationitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("disposition", "superseded"),
                                ("replacement__isnull", False),
                            ),
                            models.Q(
                                (
                                    "disposition__in",
                                    ["current_actionable", "withdrawn"],
                                ),
                                ("replacement__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="additional_disposition_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="additionalinformationitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("replacement_id", models.F("id")), _negated=True
                        ),
                        name="additional_not_own_replacement",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submissionreceiptoccurrence",
                    constraint=models.CheckConstraint(
                        condition=models.Q(disposition="queued", outbox__isnull=False)
                        | models.Q(
                            disposition="no_deliverable_recipient", outbox__isnull=True
                        ),
                        name="submission_receipt_disposition",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="submissionreceiptoccurrence",
                    constraint=models.CheckConstraint(
                        condition=models.Q(preparation__isnull=True),
                        name="submission_receipt_scrubbed",
                    ),
                ),
            ]
        ),
    ]
