# Generated by Django 5.2.17 on 2026-09-10 01:35

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stewardship_accounts", "0021_operator_recovery_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=254)),
                ("timezone", models.CharField(max_length=254)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("values", models.JSONField()),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_configurations",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign_configuration",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("state", models.CharField(default="draft", max_length=24)),
                (
                    "active_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaignconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField(db_index=True)),
                ("campaign_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=24)),
                ("due_at", models.DateTimeField(null=True)),
                ("values", models.JSONField()),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_revisions",
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_schedule_revision",
            },
        ),
        migrations.AddConstraint(
            model_name="campaignconfiguration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"),
                name="campaign_projection_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignconfiguration",
            constraint=models.UniqueConstraint(
                fields=("configuration", "name"), name="campaign_projection_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="campaign_ordered_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignconfiguration",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="campaign_ordered_instants",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_campaign_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("state", "draft")), name="campaign_draft_subset"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                models.Value(1), name="campaign_one_draft_subset"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerevision",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"), name="schedule_revision_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("due_at__isnull", False), ("kind__in", ["initial", "reminder"])
                    ),
                    models.Q(
                        ("due_at__isnull", True),
                        ("kind__in", ["daily_digest", "weekly_digest"]),
                    ),
                    _connector="OR",
                ),
                name="schedule_revision_due_kind",
            ),
        ),
    ]
