# Generated by Django 5.2.17 on 2026-09-10 10:11

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0023_phase1a_runtime"),
        ("stewardship_campaigns", "0002_campaign_guards"),
        ("stewardship_jobs", "0002_taskrun_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationCatchUpDemand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("cutoff", parishkit.stewardship.storage.UTCDateTimeField()),
                ("source_snapshot_id", models.UUIDField(null=True)),
                ("phase", models.CharField(default="pending", max_length=32)),
                ("cursor", models.CharField(default="", max_length=128)),
                ("groups_completed", models.PositiveBigIntegerField(default=0)),
                ("items_completed", models.PositiveBigIntegerField(default=0)),
                (
                    "completed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("failure_code", models.CharField(default="", max_length=64)),
            ],
            options={
                "db_table": "stewardship_activation_catchup",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignBoundaryOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("kind", models.CharField(max_length=8)),
                ("task_fence", models.PositiveBigIntegerField(null=True)),
                ("due_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("state", models.CharField(default="pending", max_length=16)),
                (
                    "completed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("reason", models.CharField(default="", max_length=64)),
            ],
            options={
                "db_table": "stewardship_campaign_boundary",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("action", models.CharField(max_length=24)),
                ("expected_version", models.PositiveBigIntegerField()),
                ("expected_runtime_version", models.PositiveBigIntegerField()),
                ("before_state", models.CharField(max_length=24)),
                ("after_state", models.CharField(max_length=24)),
                ("before_mode", models.CharField(max_length=16)),
                ("after_mode", models.CharField(max_length=16)),
                ("boundary_id", models.UUIDField(null=True)),
                ("task_fence", models.PositiveBigIntegerField(null=True)),
                ("token_generation_id", models.UUIDField(null=True)),
                ("reason", models.CharField(default="", max_length=1024)),
            ],
            options={
                "db_table": "stewardship_campaign_transition",
            },
        ),
        migrations.CreateModel(
            name="CatchUpCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("group_key", models.CharField(max_length=128)),
                ("cursor", models.CharField(max_length=128)),
                ("items", models.PositiveBigIntegerField()),
                ("fence", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "stewardship_catchup_checkpoint",
            },
        ),
        migrations.CreateModel(
            name="OccurrenceTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("before_state", models.CharField(max_length=24, null=True)),
                ("after_state", models.CharField(max_length=24)),
                ("fence", models.PositiveBigIntegerField()),
                ("attempts", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=64)),
                ("retry_command_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "stewardship_occurrence_transition",
            },
        ),
        migrations.CreateModel(
            name="PostCloseMailResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("mode", models.CharField(max_length=16)),
                ("obligation_key", models.CharField(max_length=256)),
                ("coverage_digest", models.CharField(max_length=64)),
                ("coverage", models.JSONField()),
                ("reason", models.CharField(max_length=1024)),
                ("outbox_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "stewardship_postclose_resolution",
            },
        ),
        migrations.CreateModel(
            name="RestoreDeliveryHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("restore_id", models.UUIDField()),
                ("mode", models.CharField(max_length=16)),
                ("target", models.CharField(max_length=128)),
                ("slot", models.CharField(max_length=128)),
                ("backup_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("window_start", parishkit.stewardship.storage.UTCDateTimeField()),
                ("window_end", parishkit.stewardship.storage.UTCDateTimeField()),
                ("discovery", models.CharField(max_length=64)),
                ("state", models.CharField(default="unreviewed", max_length=24)),
                (
                    "resolved_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("evidence", models.CharField(default="", max_length=1024)),
            ],
            options={
                "db_table": "stewardship_restore_delivery_hold",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RestoreHoldResolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("state", models.CharField(max_length=24)),
                ("evidence", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "stewardship_restore_hold_resolution",
            },
        ),
        migrations.CreateModel(
            name="RuntimeTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("expected_version", models.PositiveBigIntegerField(unique=True)),
                ("action", models.CharField(max_length=24)),
                ("before_mode", models.CharField(max_length=16)),
                ("after_mode", models.CharField(max_length=16)),
                ("before_campaign_id", models.UUIDField(null=True)),
                ("after_campaign_id", models.UUIDField(null=True)),
                ("restore_id", models.UUIDField(null=True)),
                (
                    "backup_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("reason", models.CharField(default="", max_length=1024)),
            ],
            options={
                "db_table": "stewardship_runtime_transition",
            },
        ),
        migrations.CreateModel(
            name="ScheduleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("kind", models.CharField(max_length=24)),
                (
                    "removed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
            ],
            options={
                "db_table": "stewardship_schedule_definition",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleFulfillment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("mode", models.CharField(max_length=16)),
                ("target", models.CharField(max_length=128)),
                ("slot", models.CharField(max_length=128)),
                ("disposition", models.CharField(max_length=16)),
            ],
            options={
                "db_table": "stewardship_schedule_fulfillment",
            },
        ),
        migrations.CreateModel(
            name="ScheduleOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("mode", models.CharField(max_length=16)),
                ("routing", models.CharField(max_length=24)),
                ("target", models.CharField(max_length=128)),
                ("slot", models.CharField(max_length=128)),
                ("due_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("occurrence_key", models.CharField(max_length=64, unique=True)),
                ("state", models.CharField(default="pending", max_length=24)),
                ("outbox_id", models.UUIDField(null=True)),
                ("worker_id", models.UUIDField(null=True)),
                ("fence", models.PositiveBigIntegerField(default=0)),
                ("attempts", models.PositiveBigIntegerField(default=0)),
                (
                    "lease_expires_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "heartbeat_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("reason", models.CharField(default="", max_length=64)),
                ("pause_version", models.PositiveBigIntegerField(null=True)),
                ("retry_command_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "stewardship_schedule_occurrence",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "stewardship_schedule_selection",
            },
        ),
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaign_draft_subset",
        ),
        migrations.RemoveConstraint(
            model_name="campaign",
            name="campaign_one_draft_subset",
        ),
        migrations.AddField(
            model_name="campaign",
            name="active_token_generation_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="delivery_paused",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="ever_active",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="first_live_delivery_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="first_live_submission_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="pause_actor_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="pause_reason",
            field=models.CharField(db_default="", default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="campaign",
            name="pause_version",
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="paused_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="readiness_revision",
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="resumed_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="structural_locked",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "draft",
                            "scheduled",
                            "active",
                            "closed",
                            "archived",
                            "purging",
                            "purge_cleanup_failed",
                            "purged",
                        ],
                    )
                ),
                name="campaign_known_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                models.Value(1),
                condition=models.Q(
                    ("state__in", ["draft", "scheduled", "active", "closed"])
                ),
                name="campaign_one_current_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ever_active", False), ("structural_locked", True), _connector="OR"
                ),
                name="campaign_live_structure_locked",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_paused", False),
                    models.Q(
                        ("pause_actor_id__isnull", False),
                        ("pause_version__gt", 0),
                        ("paused_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="campaign_pause_evidence",
            ),
        ),
        migrations.AddField(
            model_name="activationcatchupdemand",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="activationcatchupdemand",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddField(
            model_name="activationcatchupdemand",
            name="task_root",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_jobs.taskrun",
            ),
        ),
        migrations.AddField(
            model_name="campaignboundaryoccurrence",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignboundaryoccurrence",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_jobs.taskrun",
            ),
        ),
        migrations.AddField(
            model_name="campaigntransition",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaigntransition",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddField(
            model_name="campaignboundaryoccurrence",
            name="transition",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaigntransition",
            ),
        ),
        migrations.AddField(
            model_name="activationcatchupdemand",
            name="activation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaigntransition",
            ),
        ),
        migrations.AddField(
            model_name="catchupcheckpoint",
            name="demand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.activationcatchupdemand",
            ),
        ),
        migrations.AddField(
            model_name="catchupcheckpoint",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_jobs.taskrun",
            ),
        ),
        migrations.AddField(
            model_name="postclosemailresolution",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="postclosemailresolution",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_jobs.taskrun",
            ),
        ),
        migrations.AddField(
            model_name="restoreholdresolution",
            name="hold",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.restoredeliveryhold",
            ),
        ),
        migrations.AddField(
            model_name="runtimetransition",
            name="campaign_transition",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaigntransition",
            ),
        ),
        migrations.AddField(
            model_name="scheduledefinition",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="scheduledefinition",
            name="current_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.schedulerevision",
            ),
        ),
        migrations.AddField(
            model_name="restoredeliveryhold",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="schedulefulfillment",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="scheduleoccurrence",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="scheduleoccurrence",
            name="replacement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="scheduleoccurrence",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.schedulerevision",
            ),
        ),
        migrations.AddField(
            model_name="scheduleoccurrence",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_jobs.taskrun",
            ),
        ),
        migrations.AddField(
            model_name="schedulefulfillment",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="restoreholdresolution",
            name="recovery_occurrence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="restoredeliveryhold",
            name="recovery_occurrence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="postclosemailresolution",
            name="occurrence",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="occurrencetransition",
            name="occurrence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduleoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="scheduleselection",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddField(
            model_name="scheduleselection",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.scheduledefinition",
            ),
        ),
        migrations.AddField(
            model_name="scheduleselection",
            name="previous_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_selections",
                to="stewardship_campaigns.schedulerevision",
            ),
        ),
        migrations.AddField(
            model_name="scheduleselection",
            name="selected_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activation_selections",
                to="stewardship_campaigns.schedulerevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigntransition",
            constraint=models.UniqueConstraint(
                fields=("campaign", "expected_version"),
                name="campaign_transition_version",
            ),
        ),
        migrations.AddIndex(
            model_name="campaignboundaryoccurrence",
            index=models.Index(
                fields=["state", "due_at"], name="campaign_boundary_due"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignboundaryoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_campaignboundaryoccurrence_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignboundaryoccurrence",
            constraint=models.UniqueConstraint(
                fields=("campaign", "kind", "due_at"), name="campaign_boundary_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignboundaryoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["start", "close"])),
                name="campaign_boundary_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignboundaryoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["pending", "succeeded", "skipped"])),
                name="campaign_boundary_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignboundaryoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("state", "pending"),
                        ("transition__isnull", True),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("state", "succeeded"),
                        ("transition__isnull", False),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("state", "skipped"),
                        ("transition__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="campaign_boundary_result",
            ),
        ),
        migrations.AddIndex(
            model_name="activationcatchupdemand",
            index=models.Index(
                fields=["campaign", "completed_at"], name="campaign_catchup_hold"
            ),
        ),
        migrations.AddConstraint(
            model_name="activationcatchupdemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_activationcatchupdemand_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="catchupcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("demand", "sequence"), name="catchup_checkpoint_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="catchupcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("demand", "group_key"), name="catchup_checkpoint_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_scheduledefinition_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "kind__in",
                        ["initial", "reminder", "daily_digest", "weekly_digest"],
                    )
                ),
                name="schedule_definition_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_revision__isnull", False),
                        ("removed_at__isnull", True),
                    ),
                    models.Q(
                        ("current_revision__isnull", True),
                        ("removed_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="schedule_selection_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleoccurrence",
            index=models.Index(
                fields=["state", "due_at"], name="schedule_occurrence_due"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_scheduleoccurrence_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.UniqueConstraint(
                fields=("revision", "mode", "target", "slot"),
                name="schedule_occurrence_semantic_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "pending",
                            "running",
                            "delivery_unknown",
                            "succeeded",
                            "skipped",
                            "coalesced",
                            "failed",
                        ),
                    )
                ),
                name="schedule_occurrence_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "production"), ("routing", "production")),
                    models.Q(("mode", "testing"), ("routing", "testing_override")),
                    _connector="OR",
                ),
                name="schedule_occurrence_routing",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("heartbeat_at__isnull", False),
                        ("lease_expires_at__isnull", False),
                        ("state", "running"),
                        ("task__isnull", False),
                        ("worker_id__isnull", False),
                    ),
                    models.Q(
                        models.Q(("state", "running"), _negated=True),
                        ("lease_expires_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="schedule_occurrence_lease",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("replacement__isnull", False), ("state", "coalesced")),
                    models.Q(
                        models.Q(("state", "coalesced"), _negated=True),
                        ("replacement__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="schedule_occurrence_replacement",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulefulfillment",
            constraint=models.UniqueConstraint(
                fields=("definition", "mode", "target", "slot"),
                name="schedule_fulfillment_semantic",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulefulfillment",
            constraint=models.CheckConstraint(
                condition=models.Q(("disposition__in", ["delivered", "coalesced"])),
                name="schedule_fulfillment_disposition",
            ),
        ),
        migrations.AddConstraint(
            model_name="restoreholdresolution",
            constraint=models.UniqueConstraint(
                fields=("hold", "version"), name="restore_hold_resolution_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="restoredeliveryhold",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_restoredeliveryhold_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="restoredeliveryhold",
            constraint=models.UniqueConstraint(
                fields=("restore_id", "definition", "mode", "target", "slot"),
                name="restore_hold_semantic",
            ),
        ),
        migrations.AddConstraint(
            model_name="restoredeliveryhold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "unreviewed",
                            "assumed_delivered",
                            "resend_authorized",
                            "not_applicable",
                        ],
                    )
                ),
                name="restore_hold_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="restoredeliveryhold",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_end__gte", models.F("window_start"))),
                name="restore_hold_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="postclosemailresolution",
            constraint=models.UniqueConstraint(
                fields=("campaign", "mode", "obligation_key", "coverage_digest"),
                name="postclose_semantic_resolution",
            ),
        ),
        migrations.AddConstraint(
            model_name="postclosemailresolution",
            constraint=models.UniqueConstraint(
                fields=["occurrence"],
                condition=models.Q(occurrence__isnull=False),
                name="postclose_occurrence_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="postclosemailresolution",
            constraint=models.UniqueConstraint(
                fields=["task"],
                condition=models.Q(task__isnull=False),
                name="postclose_task_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="postclosemailresolution",
            constraint=models.UniqueConstraint(
                fields=["outbox_id"],
                condition=models.Q(outbox_id__isnull=False),
                name="postclose_outbox_once",
            ),
        ),
        migrations.AddConstraint(
            model_name="postclosemailresolution",
            constraint=models.CheckConstraint(
                condition=models.Q(("coverage_digest__regex", "^[0-9a-f]{64}$")),
                name="postclose_coverage_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencetransition",
            constraint=models.UniqueConstraint(
                fields=("occurrence", "version"), name="occurrence_history_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="occurrencetransition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retry_command_id__isnull", False)),
                fields=("occurrence", "retry_command_id"),
                name="occurrence_retry_command",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleselection",
            constraint=models.UniqueConstraint(
                fields=("definition", "version"), name="schedule_selection_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleselection",
            constraint=models.UniqueConstraint(
                fields=("definition", "configuration"),
                name="schedule_selection_configuration",
            ),
        ),
    ]
