# Generated by Django 5.2.17 on 2026-09-10 10:17

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0004_read_guard_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignWorkGate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("request_id", models.UUIDField(unique=True)),
                ("state", models.CharField(default="preparing", max_length=16)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign_work_gate",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_campaigns_campaignworkgate_positive_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ["preparing", "running", "released", "tombstone"],
                            )
                        ),
                        name="campaign_work_gate_state",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["preparing", "running"])),
                        fields=("campaign",),
                        name="campaign_one_work_gate",
                    ),
                ],
            },
        ),
    ]
