# Generated by Django 5.2.17 on 2026-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0007_schedule_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="catchupcheckpoint",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="catchupcheckpoint",
            name="phase",
            field=models.CharField(default="enumerating", max_length=32),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql="""
DO $$ BEGIN IF EXISTS(SELECT 1 FROM stewardship_catchup_checkpoint) THEN
    RAISE EXCEPTION 'Catch-up completion history prevents reversal'
        USING ERRCODE='23514';
END IF; END $$;
""",
        ),
    ]
