# Generated by Django 5.2.17 on 2026-09-10 11:17

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0023_phase1a_runtime"),
        ("stewardship_campaigns", "0009_boundary_catchup_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigntransition",
            name="prior_projection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_campaigns.campaignconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="CampaignConfigurationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("action", models.CharField(max_length=16)),
                ("expected_version", models.PositiveBigIntegerField()),
                ("expected_runtime_version", models.PositiveBigIntegerField()),
                ("token_generation_id", models.UUIDField(null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "prior_projection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaignconfiguration",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.configurationchangerequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign_config_intent",
            },
        ),
    ]
