# Generated by Django 5.2.17 on 2026-09-10 11:21

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0011_exceptional_end_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignControlChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("expected_version", models.PositiveBigIntegerField()),
                ("expected_runtime_version", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=24)),
                ("reason", models.CharField(default="", max_length=1024)),
                ("evidence_id", models.UUIDField(null=True)),
                ("occurred_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign_control",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "expected_version"),
                        name="campaign_control_version",
                    )
                ],
            },
        ),
    ]
