# Generated by Django 5.2.17 on 2026-09-10 16:04

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("stewardship_campaigns", "0017_catchup_failure"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialKeyState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("kind", models.CharField(max_length=32, unique=True)),
                ("inventory_digest", models.CharField(max_length=64)),
                ("inventory", models.JSONField()),
            ],
            options={
                "db_table": "stewardship_credential_key_state",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_campaigns_credentialkeystate_positive_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentCredentialState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("family_link_epoch", models.UUIDField(default=uuid.uuid4)),
                ("restore_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "stewardship_credential_deployment",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_campaigns_deploymentcredentialstate_positive_version",
                    ),
                    models.UniqueConstraint(
                        models.Value(1), name="credential_deployment_singleton"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FamilyAccessTokenGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("operation_id", models.UUIDField(unique=True)),
                ("task_id", models.UUIDField(null=True)),
                ("credential_epoch", models.UUIDField()),
                ("restore_id", models.UUIDField(null=True)),
                ("preparation_revision", models.PositiveBigIntegerField(default=1)),
                ("source_snapshot_id", models.UUIDField()),
                ("source_generation", models.PositiveBigIntegerField()),
                ("key_id", models.CharField(max_length=48)),
                ("key_inventory_digest", models.CharField(max_length=64)),
                ("coverage_digest", models.CharField(default="", max_length=64)),
                ("coverage_count", models.PositiveBigIntegerField(default=0)),
                ("checkpoint", models.PositiveBigIntegerField(default=0)),
                (
                    "completed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("state", models.CharField(default="building", max_length=16)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaignconfiguration",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_token_generation",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamilyCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("family_duid", models.PositiveBigIntegerField()),
                ("active", models.BooleanField()),
                ("portal_eligible", models.BooleanField()),
                ("email_eligible", models.BooleanField()),
                ("email_deliverable", models.BooleanField()),
                ("status_reason", models.CharField(max_length=48)),
                ("deliverability_reason", models.CharField(max_length=48)),
                (
                    "first_eligible_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "first_eligible_source_generation",
                    models.PositiveBigIntegerField(null=True),
                ),
                (
                    "eligibility_changed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(),
                ),
                ("source_generation", models.PositiveBigIntegerField()),
                ("code_ciphertext", models.TextField(null=True)),
                (
                    "initial_invitation_state",
                    models.CharField(default="not_sent", max_length=24),
                ),
                ("first_live_submission_id", models.UUIDField(null=True)),
                ("effective_submission_id", models.UUIDField(null=True)),
                (
                    "last_activity_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_campaign",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamilyAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("ciphertext", models.TextField(null=True)),
                ("digest", models.CharField(max_length=64, null=True)),
                (
                    "destroyed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "revoked_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familyaccesstokengeneration",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familycampaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_token",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FamilyCodeFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("key_id", models.CharField(max_length=48)),
                (
                    "algorithm",
                    models.CharField(default="hmac-sha256-v1", max_length=24),
                ),
                ("digest", models.CharField(max_length=64)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familycampaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_code_mac",
            },
        ),
        migrations.CreateModel(
            name="FamilyEligibilityChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("source_generation", models.PositiveBigIntegerField()),
                ("family_version", models.PositiveBigIntegerField()),
                ("active", models.BooleanField()),
                ("portal_eligible", models.BooleanField()),
                ("email_eligible", models.BooleanField()),
                ("email_deliverable", models.BooleanField()),
                ("status_reason", models.CharField(max_length=48)),
                ("deliverability_reason", models.CharField(max_length=48)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familycampaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_eligibility",
            },
        ),
        migrations.CreateModel(
            name="RehearsalCodeReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.CharField(max_length=48)),
                (
                    "algorithm",
                    models.CharField(default="hmac-sha256-v1", max_length=24),
                ),
                ("digest", models.CharField(max_length=64)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_rehearsal_reservation",
            },
        ),
        migrations.CreateModel(
            name="RehearsalEpoch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                (
                    "invalidated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("state", models.CharField(default="active", max_length=16)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_rehearsal_epoch",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RehearsalCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("code_ciphertext", models.TextField()),
                ("token_ciphertext", models.TextField()),
                ("token_digest", models.CharField(max_length=64)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familycampaign",
                    ),
                ),
                (
                    "epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.rehearsalepoch",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_rehearsal_credential",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RehearsalCodeFingerprint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("key_id", models.CharField(max_length=48)),
                (
                    "algorithm",
                    models.CharField(default="hmac-sha256-v1", max_length=24),
                ),
                ("digest", models.CharField(max_length=64)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.rehearsalcredential",
                    ),
                ),
                (
                    "epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.rehearsalepoch",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_rehearsal_code_mac",
            },
        ),
        migrations.CreateModel(
            name="FamilySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("mode", models.CharField(max_length=16)),
                ("authenticated_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("last_activity_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "last_keepalive_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("expires_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "revoked_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.familycampaign",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sessions.session",
                    ),
                ),
                (
                    "rehearsal_epoch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.rehearsalepoch",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_family_session",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignCredentialState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("go_live_gate", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_state",
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "rehearsal_epoch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.rehearsalepoch",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_campaign_credentials",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="familyaccesstokengeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_familyaccesstokengeneration_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstokengeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "building",
                            "ready",
                            "active",
                            "failed",
                            "cancelled",
                            "superseded",
                        ],
                    )
                ),
                name="family_token_generation_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstokengeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["ready", "active"]), _negated=True),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("coverage_digest__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="family_token_ready_manifest",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_familycampaign_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.UniqueConstraint(
                fields=("campaign", "family_duid"), name="family_campaign_duid"
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("family_duid__gt", 0)),
                name="family_campaign_positive_duid",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("portal_eligible", False),
                    models.Q(
                        ("active", True),
                        ("code_ciphertext__isnull", False),
                        ("first_eligible_at__isnull", False),
                        ("first_eligible_source_generation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="family_eligible_has_code_cohort",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("first_eligible_at__isnull", True),
                        ("first_eligible_source_generation__isnull", True),
                    ),
                    models.Q(
                        ("first_eligible_at__isnull", False),
                        ("first_eligible_source_generation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="family_cohort_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email_deliverable", False),
                    ("email_eligible", True),
                    _connector="OR",
                ),
                name="family_deliverable_is_eligible",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_familyaccesstoken_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstoken",
            constraint=models.UniqueConstraint(
                fields=("family", "generation"), name="family_token_generation_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstoken",
            constraint=models.UniqueConstraint(
                fields=("campaign", "digest"), name="family_token_campaign_digest"
            ),
        ),
        migrations.AddConstraint(
            model_name="familyaccesstoken",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ciphertext__isnull", False),
                        ("destroyed_at__isnull", True),
                        ("digest__isnull", False),
                    ),
                    models.Q(
                        ("ciphertext__isnull", True),
                        ("destroyed_at__isnull", False),
                        ("digest__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="family_token_destroyed_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="familycodefingerprint",
            constraint=models.UniqueConstraint(
                fields=("family", "key_id"), name="family_code_key_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="familycodefingerprint",
            constraint=models.UniqueConstraint(
                fields=("campaign", "key_id", "digest"), name="campaign_code_key_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="familycodefingerprint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("algorithm", "hmac-sha256-v1"), ("digest__regex", "^[0-9a-f]{64}$")
                ),
                name="family_code_mac_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyeligibilitychange",
            constraint=models.UniqueConstraint(
                fields=("family", "family_version"), name="family_eligibility_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcodereservation",
            constraint=models.UniqueConstraint(
                fields=("campaign", "key_id", "algorithm", "digest"),
                name="rehearsal_reservation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalepoch",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_rehearsalepoch_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalepoch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("campaign",),
                name="campaign_one_rehearsal_epoch",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalepoch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("invalidated_at__isnull", True), ("state", "active")),
                    models.Q(
                        ("invalidated_at__isnull", False), ("state", "invalidated")
                    ),
                    _connector="OR",
                ),
                name="rehearsal_epoch_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcredential",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_rehearsalcredential_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcredential",
            constraint=models.UniqueConstraint(
                fields=("epoch", "family"), name="rehearsal_epoch_family_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcredential",
            constraint=models.UniqueConstraint(
                fields=("epoch", "token_digest"), name="rehearsal_epoch_token_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcodefingerprint",
            constraint=models.UniqueConstraint(
                fields=("credential", "key_id"), name="rehearsal_code_key_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcodefingerprint",
            constraint=models.UniqueConstraint(
                fields=("epoch", "key_id", "digest"),
                name="rehearsal_epoch_code_key_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="familysession",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_familysession_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="familysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "production"), ("rehearsal_epoch__isnull", True)),
                    models.Q(("mode", "testing"), ("rehearsal_epoch__isnull", False)),
                    _connector="OR",
                ),
                name="family_session_mode_epoch",
            ),
        ),
        migrations.AddConstraint(
            model_name="familysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_activity_at__gte", models.F("authenticated_at")),
                    ("expires_at__gt", models.F("last_activity_at")),
                ),
                name="family_session_chronology",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigncredentialstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_campaigns_campaigncredentialstate_positive_version",
            ),
        ),
    ]
