# Generated by Django 5.2.17 on 2026-09-10 16:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0019_credential_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="familysession",
            name="credential_epoch",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
