# Generated by Django 5.2.17 on 2026-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0020_familysession_credential_epoch"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncredentialstate",
            name="eligibility_digest",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="campaigncredentialstate",
            name="eligible_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaigncredentialstate",
            name="source_generation",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="campaigncredentialstate",
            name="source_snapshot_id",
            field=models.UUIDField(null=True),
        ),
    ]
