# Generated by Django 5.2.17 on 2026-09-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "stewardship_campaigns",
            "0021_campaigncredentialstate_eligibility_digest_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncredentialstate",
            name="population_dirty",
            field=models.BooleanField(default=True),
        ),
    ]
