# Generated by Django 5.2.17 on 2026-09-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0026_auth_incident_guards"),
        ("stewardship_campaigns", "0024_rehearsal_cleanup_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyaccesstokengeneration",
            name="configuration_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="stewardship_accounts.configurationchangerequest",
            ),
        ),
    ]
