# Generated by Django 5.2.17 on 2026-09-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0027_current_token_issuance_guard"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rehearsalcodefingerprint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("algorithm", "hmac-sha256-v1"), ("digest__regex", "^[0-9a-f]{64}$")
                ),
                name="rehearsal_code_mac_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="rehearsalcodereservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("algorithm", "hmac-sha256-v1"), ("digest__regex", "^[0-9a-f]{64}$")
                ),
                name="rehearsal_reservation_format",
            ),
        ),
    ]
